In [1]:
import numpy as pd
import pandas as pd
import ast

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

# mearging the two data sets

In [3]:
movies = movies.merge(credits,on='title')

In [4]:
#movies.head(1)

 # feature selection of the movies dataset:
1.genres
 
2.id
 
3.keywords

4.title

5.overview

6.Cast

7.Crew

In [5]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [6]:
movies.head(4000)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
3995,13025,Diary of the Dead,A group of young film students run into real-l...,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 28, ""nam...","[{""id"": 12377, ""name"": ""zombie""}, {""id"": 16305...","[{""cast_id"": 3, ""character"": ""Debra Moynihan"",...","[{""credit_id"": ""52fe45319251416c7504eab9"", ""de..."
3996,21461,Lage Raho Munna Bhai,A hilarious underworld gangster known as Munna...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 6165, ""name"": ""historical figure""}, {""...","[{""cast_id"": 9, ""character"": ""Murli Prasad Sha...","[{""credit_id"": ""52fe441ac3a368484e00f9c3"", ""de..."
3997,55306,Ulee's Gold,An elderly beekeeper and Vietnam vet must resc...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 494, ""name"": ""father son relationship""...","[{""cast_id"": 12, ""character"": ""Ulee Jackson"", ...","[{""credit_id"": ""570af9c19251417da7001777"", ""de..."
3998,17264,The Black Stallion,"While traveling with his father, young Alec be...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 10751...","[{""id"": 383, ""name"": ""poker""}, {""id"": 2673, ""n...","[{""cast_id"": 1, ""character"": ""Alec Ramsey"", ""c...","[{""credit_id"": ""54ee5070925141795f004b0c"", ""de..."
3999,346081,Sardaarji,A ghost hunter uses bottles to capture trouble...,[],[],[],"[{""credit_id"": ""558ab3f4925141076f0001d7"", ""de..."

In [7]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

# Data preprocessing removing duplicate data and looking for missing data

# for null value

In [8]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [9]:
movies.dropna(inplace = True)

# for duplicate data

In [10]:
movies.duplicated().sum()

0

In [11]:
movies.drop_duplicates(subset=['genres'],inplace = True)

In [12]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [13]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [14]:
movies['genres'] = movies['genres'].apply(convert)

In [15]:
movies['keywords']=movies['keywords'].apply(convert)

In [16]:
def convert3(obj):
    L=[]
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter += 1
        else:
            break
    return L

In [17]:
movies['cast']=movies['cast'].apply(convert3)

In [18]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [19]:
movies['crew']=movies['crew'].apply(fetch_director)

In [20]:
movies['crew']

0            [James Cameron]
1           [Gore Verbinski]
2               [Sam Mendes]
3        [Christopher Nolan]
4           [Andrew Stanton]
                ...
4794           [John Waters]
4798      [Kiyoshi Kurosawa]
4800    [Thomas L. Phillips]
4803      [Neill Dela Llana]
4806           [Scott Smith]
Name: crew, Length: 1175, dtype: object

In [21]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [22]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" "," ")for i in x])

In [23]:
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" "," ")for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" "," ")for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" "," ")for i in x])

In [24]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

# making a colume as Tage , concading all the colume into tags

In [25]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [26]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [27]:
new_df = movies[['movie_id','title','tags']]

In [28]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

<ipython-input-28-ad44e9ca1347>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [29]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d Sam Worthington Zoe Saldana Sigourney Weaver James Cameron'

In [30]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [31]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

<ipython-input-31-8b60b591a07f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [32]:
new_df['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drug abuse exotic island east india trading company love of one's life traitor shipwreck strong woman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnny depp orlando bloom keira knightley gore verbinski"

# Count Vectorization

In [33]:
from sklearn.feature_extraction.text import CountVectorizer

# how perform stamming in the above data using NLTK 
stemming = to take out the root word of the given word

In [34]:
import nltk

In [35]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [36]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [37]:
new_df['tags'] = new_df['tags'].apply(stem)

<ipython-input-37-be18a4346d89>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [38]:
cv = CountVectorizer(max_features = 5000,stop_words = 'english')

In [39]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [40]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [41]:
cv.get_feature_names()

['000',
 '10',
 '10th',
 '11',
 '12',
 '14',
 '15',
 '15th',
 '16',
 '16th',
 '17',
 '18',
 '1890',
 '18th',
 '1910',
 '1920',
 '1930',
 '1941',
 '1950',
 '1960',
 '1970',
 '1972',
 '1974',
 '1980',
 '1985',
 '19th',
 '20',
 '2001',
 '20th',
 '21st',
 '22nd',
 '30',
 '300',
 '3d',
 '50',
 '51',
 '60',
 '60s',
 '70',
 'aaron',
 'abandon',
 'abduct',
 'abel',
 'abigail',
 'abil',
 'abl',
 'aboard',
 'aborigin',
 'abraham',
 'abroad',
 'abus',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'act',
 'action',
 'activ',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolf',
 'adonijah',
 'adopt',
 'ador',
 'adrian',
 'adrien',
 'adult',
 'adulteri',
 'adulthood',
 'adults',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'affair',
 'affect',
 'affleck',
 'afghanistan',
 'africa',
 'african',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'age',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidan',
 'air',
 'airplan',
 'airport',
 'akshay',
 'al',
 'alan',
 'alba',
 'alcohol',
 'alec',
 'alejandro',
 'alex',
 'alexa',
 'alexand',
 'alexi',
 'ali',
 'alic',
 'alice',
 'alicia',
 'alien',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allan',
 'alleg',
 'allen',
 'alli',
 'allianc',
 'allow',
 'almási',
 'alon',
 'alreadi',
 'alter',
 'altern',
 'altman',
 'alway',
 'amadeo',
 'amanda',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'amber',
 'ambit',
 'ambiti',
 'ambush',
 'amelia',
 'america',
 'american',
 'ami',
 'amid',
 'amidst',
 'amiel',
 'amnesia',
 'amp',
 'amus',
 'anakin',
 'anarch',
 'ancient',
 'anderson',
 'andi',
 'andrew',
 'android',
 'ang',
 'angarano',
 'angel',
 'angela',
 'angeles',
 'angelina',
 'anger',
 'angri',
 'ani',
 'anim',
 'animals',
 'aniston',
 'anita',
 'ann',
 'anna',
 'annaud',
 'annett',
 'anni',
 'announc',
 'anonym',
 'anoth',
 'answer',
 'antarctica',
 'anthoni',
 'anthropomorph',
 'anti',
 'antoin',
 'anton',
 'antonio',
 'anyon',
 'anyth',
 'apart',
 'apartment',
 'ape',
 'apes',
 'apocalyps',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'apprentic',
 'approach',
 'april',
 'arab',
 'arabia',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'archeri',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'ari',
 'arizona',
 'arlo',
 'arm',
 'armi',
 'armor',
 'army',
 'arnett',
 'arnold',
 'arquett',
 'arrang',
 'arrest',
 'arriv',
 'arrow',
 'art',
 'arthur',
 'artifici',
 'artist',
 'ash',
 'ashley',
 'asid',
 'ask',
 'asleep',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assignment',
 'assist',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atkin',
 'atlant',
 'atom',
 'attack',
 'attempt',
 'attend',
 'attic',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'aurora',
 'austen',
 'austin',
 'australia',
 'australian',
 'austria',
 'author',
 'auto',
 'automaton',
 'automobil',
 'aveng',
 'averag',
 'averil',
 'avoid',
 'await',
 'awaken',
 'award',
 'away',
 'awkward',
 'ayer',
 'aykroyd',
 'azaria',
 'baader',
 'babe',
 'babi',
 'baby',
 'bachchan',
 'backdrop',
 'background',
 'backstag',
 'bacon',
 'bad',
 'bahama',
 'bail',
 'baker',
 'balanc',
 'baldwin',
 'bale',
 'ball',
 'ballet',
 'balloon',
 'balthazar',
 'baltimor',
 'bam',
 'bana',
 'band',
 'bandera',
 'banish',
 'bank',
 'bar',
 'barbara',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrier',
 'barrymor',
 'bart',
 'baruchel',
 'base',
 'basebal',
 'basement',
 'basing',
 'basketbal',
 'basketball',
 'bassett',
 'bat',
 'bath',
 'batman',
 'battalion',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'baz',
 'beach',
 'bean',
 'bear',
 'beard',
 'beast',
 'beat',
 'beatti',
 'beauti',
 'becam',
 'becaus',
 'beck',
 'beckinsal',
 'becom',
 'bed',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belgium',
 'belief',
 'believ',
 'bell',
 'belov',
 'ben',
 'bene',
 'beneath',
 'benedict',
 'benicio',
 'benjamin',
 'bennett',
 'bent',
 'bentley',
 'berg',
 'berlin',
 'berri',
 'besson',
 'best',
 'bet',
 'betray',
 'betrayal',
 'betroth',
 'bettani',
 'better',
 'betti',
 'bibl',
 'bieber',
 'big',
 'biggest',
 'billi',
 'billionair',
 'bin',
 'biographi',
 'biolog',
 'biologist',
 'bird',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bite',
 'bitten',
 'bitter',
 'bizarr',
 'black',
 'blackmail',
 'blacksmith',
 'blade',
 'blake',
 'blame',
 'blanchett',
 'blast',
 'blaze',
 'bledel',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodthirsti',
 'bloom',
 'blow',
 'blue',
 'blunt',
 'boar',
 'board',
 'boat',
 'bob',
 'bobbi',
 'bobin',
 'bodi',
 'body',
 'bodyguard',
 'boll',
 'bollywood',
 'bomb',
 'bond',
 'bondarchuk',
 'bone',
 'bonham',
 'boo',
 'book',
 'boots',
 'boov',
 'border',
 'bore',
 'born',
 'boss',
 'boston',
 'bosworth',
 'bounti',
 'bow',
 'bower',
 'box',
 'boxer',
 'boy',
 'boyd',
 'boyfriend',
 'boys',
 'brad',
 'bradford',
 'bradley',
 'braga',
 'brain',
 'brainwash',
 'branagh',
 'brand',
 'brandi',
 'brandon',
 'bratt',
 'brave',
 'braveri',
 'break',
 'breed',
 'brendan',
 'brent',
 'breslin',
 'brett',
 'brian',
 'bride',
 'bridg',
 'brief',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britt',
 'brittani',
 'broadbent',
 'broadway',
 'brock',
 'broderick',
 'brodi',
 'broke',
 'broken',
 'brolin',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brosnan',
 'brothel',
 'brother',
 'brotherhood',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'brutal',
 'bryan',
 'bryce',
 'bu',
 'buddhist',
 'buddi',
 'buddy',
 'buffalo',
 'build',
 'bullet',
 'bulli',
 'bullock',
 'bumbl',
 'bumpi',
 'burglar',
 'buri',
 'burn',
 'burton',
 'busi',
 'business',
 'businessman',
 'butch',
 'butcher',
 'butler',
 'buy',
 'byrn',
 'cab',
 'cabin',
 'cabl',
 'caesar',
 'cage',
 'cain',
 'cairo',
 'california',
 'calli',
 'calvin',
 'cam',
 'came',
 'camelot',
 'cameo',
 'camera',
 'cameraman',
 'cameron',
 'camp',
 'campaign',
 'campanella',
 'campbel',
 'canada',
 'canadian',
 'canari',
 'cancer',
 'capabl',
 'capone',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'captured',
 'car',
 'care',
 'career',
 'carel',
 'carey',
 'cari',
 'carl',
 'carla',
 'carlo',
 'carmen',
 'carniv',
 'carnivor',
 'carol',
 'carpent',
 'carradin',
 'carrey',
 'carri',
 'carrie',
 'carter',
 'cartoon',
 'case',
 'casey',
 'cash',
 'casino',
 'cassavet',
 'cassidi',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cate',
 'catherin',
 'cathol',
 'catholic',
 'cattl',
 'cattral',
 'catwoman',
 'caught',
 'caus',
 'cave',
 'cavemen',
 'cavendich',
 'cecil',
 'celebr',
 'cell',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'ceremoni',
 'certain',
 'cgi',
 'chain',
 'challeng',
 'champion',
 'championship',
 'chan',
 'chanc',
 'chaney',
 'chang',
 'change',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charl',
 'charli',
 'charliz',
 'charlott',
 'charm',
 'chart',
 'chase',
 'chastain',
 'chauffeur',
 'cheat',
 'chelsom',
 'chemic',
 'chest',
 'chestnut',
 'chicago',
 'chick',
 'chief',
 'child',
 'childhood',
 'childless',
 'children',
 'chili',
 'chill',
 'chimp',
 'china',
 'chinatown',
 'chines',
 'chip',
 'chipett',
 'chipmunk',
 'chloë',
 'chocol',
 'choic',
 'choir',
 'chon',
 'choos',
 'chosen',
 'chou',
 'chow',
 'chri',
 'christ',
 'christensen',
 'christian',
 'christin',
 'christina',
 'christma',
 'christmas',
 'christoph',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'cinderella',
 'cinema',
 'circl',
 'circle',
 'circu',
 'circumst',
 'cirqu',
 'citi',
 'citizen',
 'city',
 'civil',
 'claim',
 'clair',
 'clan',
 'clare',
 'clari',
 'clark',
 'clash',
 'class',
 'classic',
 'clau',
 'claud',
 'claustrophobia',
 'clay',
 'clean',
 'clear',
 'clement',
 'client',
 'cliff',
 'clifford',
 'climb',
 'clint',
 'cliqu',
 'clive',
 'clock',
 'clone',
 'clooney',
 'close',
 'cloud',
 'clown',
 'club',
 'clue',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'cody',
 'coen',
 'coerc',
 'coffin',
 'cohen',
 'cold',
 'cole',
 'coleridg',
 'colin',
 'collaps',
 'colleagu',
 'colleague',
 'collect',
 'collector',
 'colleg',
 'college',
 'collet',
 'collid',
 'collin',
 'colon',
 'colonel',
 'coloni',
 'color',
 'coma',
 'combat',
 'combin',
 'come',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'command',
 'commando',
 'commentari',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'compil',
 'complet',
 'complex',
 'complic',
 'compos',
 'compromis',
 'comput',
 'concert',
 'confeder',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'connect',
 'connelli',
 'conneri',
 'conni',
 'connor',
 'conquer',
 'conquest',
 'conrad',
 'conscienc',
 'consequ',
 'consequences',
 'conspiraci',
 'construct',
 'consum',
 'contact',
 'contain',
 'contamin',
 'contend',
 'contest',
 'contin',
 'continu',
 'contract',
 'control',
 'controversi',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'coraci',
 'core',
 'corner',
 'corp',
 'corpor',
 'corps',
 'correspond',
 'corrupt',
 'cortez',
 'cost',
 'costner',
 'costum',
 'count',
 'countri',
 'country',
 'countrysid',
 'countryside',
 'coup',
 'coupl',
 'couple',
 'courag',
 'cours',
 'court',
 'courteney',
 'cover',
 'covert',
 'cow',
 'coward',
 'cowardli',
 'cowboy',
 'cox',
 'crack',
 'craft',
 'craig',
 'crash',
 'crave',
 'craven',
 'crawford',
 'crazi',
 'creat',
 'creation',
 'creator',
 'creatur',
 'creature',
 'creatures',
 'credit',
 'crew',
 'crime',
 'crimes',
 'crimin',
 'criminal',
 'criminals',
 'crisi',
 'critic',
 'crocodil',
 'cronenberg',
 'crook',
 'crop',
 'cross',
 'crossroad',
 'crow',
 'crown',
 'cruel',
 'cruis',
 'cruise',
 'crumbl',
 'crush',
 'cruz',
 'crystal',
 'cuba',
 'cube',
 'culkin',
 'culmin',
 'cult',
 'cultur',
 'cure',
 'current',
 'curs',
 'curse',
 'curti',
 'cusack',
 'custody',
 'cut',
 'cyber',
 'cyberpunk',
 'cyborg',
 'cynic',
 'cyru',
 'dad',
 'dafo',
 'daili',
 'dakota',
 'daley',
 'dalla',
 'damag',
 'damon',
 'dan',
 'dana',
 'danc',
 'dance',
 'dancer',
 'dane',
 'danger',
 'daniel',
 'danni',
 'danny',
 'danson',
 'dant',
 'darci',
 'dare',
 'dark',
 'darkest',
 'darkness',
 'darnel',
 'darren',
 'daryl',
 'dash',
 'dastardli',
 'date',
 'daughter',
 'dave',
 'davi',
 'david',
 'davidson',
 'dawn',
 'dawson',
 'day',
 'daydream',
 'days',
 'dc',
 'dead',
 'deadli',
 'deadliest',
 'deal',
 'dealer',
 'dean',
 'death',
 'debt',
 'decad',
 'decapit',
 'deceas',
 'deceit',
 'decept',
 ...]

In [42]:
from sklearn.metrics.pairwise import cosine_similarity

In [43]:
similarity = cosine_similarity(vectors)

In [44]:
similarity[0]

array([1.        , 0.06454972, 0.06388766, ..., 0.        , 0.01123666,
       0.04225771])

# funtion to recommend moives , if give input to the function it will game names of similar 5 movies

In [45]:
sorted(list(enumerate(similarity[0])),reverse = True , key = lambda x:x[1])[1:6]

[(628, 0.37824503556648703),
 (437, 0.3587150269897196),
 (715, 0.3493335058437492),
 (192, 0.32896917898295686),
 (175, 0.3144716283916423)]

In [46]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse = True , key = lambda x:x[1])[1:6]
    for i in movies_list:
        
        print(new_df.iloc[i[0]].title)

In [47]:
recommend('Batman Begins')

Kung Fu Panda 3
Legend of a Rabbit
Kung Fu Hustle
Bulletproof Monk
3 Ninjas Kick Back

In [48]:
import pickle

In [53]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [54]:
pickle.dump(new_df,open('movies_dict.pkl','wb'))

In [50]:
pickle.dump(similarity,open("similarity1.pkl",'wb'))

In [51]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True,key=lambda x:x[1])[1:6]

    recommend_movies = []
    for i in movies_list:
        recommend_movies.append(movies.iloc[i[0]].title)

    return(recommend_movies)

In [52]:
recommend('Batman Begins')

['Kung Fu Panda 3',
 'Legend of a Rabbit',
 'Kung Fu Hustle',
 'Bulletproof Monk',
 '3 Ninjas Kick Back']